### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by ElGittoJunior** [victor-prdh/recaptcha-bundle#1]
Hello my friend!

Thank you for the Bundle, very useful!

Here are some german translations:

verify.captcha: "Bitte verifizieren Sie das Captcha"
invalid.captcha: "Captcha ungültig, bitte versuchen Sie es erneut"
timeout.captcha: "Das Captcha ist nicht mehr gültig, bitte versuchen Sie es noch einmal"
missinginput.captcha: "Leerer Geheimschlüssel"
invalidinput.captcha: "Ungültiger Geheimschlüssel"
hostname.captcha: "Hostname stimmt nicht überein"
badrequest.captcha: "Die Anfrage konnte nicht abgeschlossen werden"

[victorprdh_recaptcha.de.yaml.zip](https://github.com/victor-prdh/recaptcha-bundle/files/9598154/victorprdh_recaptcha.de.yaml.zip)

**Comment by victor-prdh** [comment]
Hello El Gitto, 

Thank you very much for that, i add it right now !
