### ISSUE TITLE
Deprecation on Symfony\Component\Config\Definition\ConfigurationInterface::getConfigTreeBuilder()

### ISSUE THREAD

**Issue by pierrealexaline** [victor-prdh/recaptcha-bundle#4]
Method "Symfony\Component\Config\Definition\ConfigurationInterface::getConfigTreeBuilder()" might add "TreeBuilder" as a native return type declaration in the future. Do the same in implementation "VictorPrdh\RecaptchaBundle\DependencyInjection\Configuration" now to avoid errors or add an explicit @return annotation to suppress this message.

Solution:

```php
<?php
#recaptcha-bundle/src/DependencyInjection/Configuration

( ... )

class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder() :TreeBuilder
    { 
    ( ... )
```

**Comment by victor-prdh** [comment]
Hi and thanks a lot !

This fix is available in the new [release](https://github.com/victor-prdh/recaptcha-bundle/releases/tag/1.7.1) !
