### ISSUE TITLE
A method must now have a return type / deprecation symfony 6.3.8 and PHP 8.3.2

### ISSUE THREAD

**Issue by pierrealexaline** [victor-prdh/recaptcha-bundle#7]
**VictorPrdh\RecaptchaBundle\DependencyInjection\RecaptchaExtension**

Method "Symfony\Component\DependencyInjection\Extension\ExtensionInterface::load()" might add "void" as a native return type declaration in the future. Do the same in implementation "VictorPrdh\RecaptchaBundle\DependencyInjection\RecaptchaExtension" now to avoid errors or add an explicit @return annotation to suppress this message.

**VictorPrdh\RecaptchaBundle\Validator\Constraints\IsValidCaptchaValidator**

Method "Symfony\Component\Validator\ConstraintValidatorInterface::validate()" might add "void" as a native return type declaration in the future. Do the same in implementation "VictorPrdh\RecaptchaBundle\Validator\Constraints\IsValidCaptchaValidator" now to avoid errors or add an explicit @return annotation to suppress this message.

**VictorPrdh\RecaptchaBundle\Form\ReCaptchaType**

Method "Symfony\Component\Form\AbstractType::buildView()" might add "void" as a native return type declaration in the future. Do the same in child class "VictorPrdh\RecaptchaBundle\Form\ReCaptchaType" now to avoid errors or add an explicit @return annotation to suppress this message.

**VictorPrdh\RecaptchaBundle\Form\ReCaptchaType**

Method "Symfony\Component\Form\AbstractType::configureOptions()" might add "void" as a native return type declaration in the future. Do the same in child class "VictorPrdh\RecaptchaBundle\Form\ReCaptchaType" now to avoid errors or add an explicit @return annotation to suppress this message.

I try to make a pull request this day.

Thx for this work.

**Comment by victor-prdh** [comment]
New release available !

Thanks again :)
